config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :todos
  root "todos#index"
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates_presence_of :name,:date,:note
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/show/todos_controller.rb
class Show::TodosController < ApplicationController
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, :only=>[:show,:edit,:update,:destroy]
  def index
    @todos=Todo.all
  end
  def new
    @todo=Todo.new
  end

  def create
    @todo=Todo.new(todo_params)
    if @todo.save
      render :action =>:show
    else
      render :action=>:new
    end
  end

  #def show
  #  @todo=Todo.find(params[:id])
  #end

  #def edit
    #@todo=Todo.find(params[:id])
  #end

  def update
    #@todo=Todo.find(params[:id])
    if @todo.update_attributes(todo_params)
      render :action =>:show
      #redirect_to todos_url
    else
      render :action =>:edit
    end
  end
  def destroy
    #@todo=Todo.find(params[:id])
    @todo.destroy

    redirect_to todos_url
  end

  private
  def todo_params
    params.require(:todo).permit(:name,:date,:note)
  end
  def set_todo
    @todo = Todo.find(params[:id])
  end





end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/show/todos_helper.rb
module Show::TodosHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoListApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<%if @todo.errors.present? %>
  <ul>
    <%@todo.errors.each do |error,message| %>
      <li> <%= "#{error.capitalize}  #{message}" %> </li>
    <%end%>
  </ul>
<%end%>

<div class="form container">

<%=form_for @todo do |f|%>
  <div class="form-group">
    <%=f.label :name ,'Name'%>
    <%=f.text_field :name ,class:"form-control"%>
  </div>

  <div class="form-group">
    <%=f.label :date ,'Date'%>
    <%=f.text_field :date ,class:"form-control"%>
  </div>

  <div class="form-group">
    <%=f.label :note ,'Note'%>
    <%=f.text_area :note ,class:"form-control"%>
  </div>
  <%=f.submit %>
<%end%>
</div>

app/views/todos/edit.html.erb
<%=render :partial =>"form"%>

app/views/todos/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link href="/app/assets/bootstrap.min.css" rel="stylesheet">
  </head>
  <body>
    <div class="container">
      <div class="title">
        <div class="title_w">
          PureBread Order List
        </div>
        <div class="order">
          <span class="a"><%= link_to 'New Order', new_todo_path %></span>
        </div>
      </div>
      <div class="list">
      <table class="table table-striped table-condensed ">
        <%@todos.each do |todo|%>
          <tr class="word2">
            <td>
              <span class="glyphicon glyphicon-ok">&#160</span>
              <%=link_to todo.name ,todo_path(todo)%>
              <span>&#160&#160&#160</span>
              <%=todo.date%>
              <span>&#160&#160&#160</span>
              <span class="dat">
                <% if (todo.date < Date.today)%>
                  expiry
                <%else%>
                  <span class="edi"><%=link_to 'Delete',todo_path(todo),method: :delete,data:{confirm: "Are you sure?"} %></span>
                <%end%>
              </span>
              <span class="edi"><%=link_to 'Edit' ,edit_todo_path(todo)%></span>

            </td>
            <td><%link_to 'Show' ,todo_path(todo)%></td>
            <td><%link_to 'Edit' ,edit_todo_path(todo)%></td>
            <td><%link_to 'Delete',todo_path(todo),method: :delete,data:{confirm: "Are you sure?"} %></td>
          </tr>
          <%end%>
        </table>


      </div>
    </div>
  </body>
</html>

app/views/todos/new.html.erb
<%=render :partial =>"form"%>

app/views/todos/show.html.erb
<div class="te">
  <div class="word">
    Todo List
  </div>
  <div class="word2">
    <span>Name: </span> <%=@todo.name%>
    <br/>
    <span>Date: </span><%=@todo.date%>
    <br/>
    <span>Note: </span><%=@todo.note%>
  </div>
  <div class="word2 word3">
    <%=link_to 'Edit' ,edit_todo_path(@todo)%>
  </div>
  <div class="word2 word3 word4">
    <%=link_to 'Back',todos_url%>
  </div>
</div>